# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Test
      run: dotnet test --no-build --verbosity normal

  artifact:
    needs: [build, test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Public
      run: | 
        dotnet publish -c Release -o bin/Release/net7.0/publish
        pwd

    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      id: download
      with:
        name: 'learning-cicd-dotnet-api'
        path: /home/runner/work/learning-cicd-dotnet-api/learning-cicd-dotnet-api/bin/Release/net7.0/publish/

    - name: 'Echo download path'
      run: echo ${{steps.download.outputs.download-path}}
